export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_IN_FETCH = 'LOG_IN_FETCH';
export const LOG_OUT = 'LOG_OUT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FETCH = 'REGISTER_FETCH';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const CREATE_ANNOUNCEMENT_FAILURE = 'CREATE_ANNOUNCEMENT_FAILURE';
export const CREATING_ANNOUNCEMENT = 'CREATING_ANNOUNCEMENT';
export const GET_ANNOUNCEMENTS_FETCH = 'GET_ANNOUNCEMENTS_FETCH';
export const GET_ANNOUNCEMENTS_SUCCESS = 'GET_ANNOUNCEMENTS_SUCCESS';
export const GET_ANNOUNCEMENTS_FAILURE = 'GET_ANNOUNCEMENTS_FAILURE';

export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_FAILURE = 'FEEDBACK_FAILURE';
export const CREATING_FEEDBACK = 'CREATING_FEEDBACK';
export const DROPDOWN_SELECTED = 'DROPDOWN_SELECTED';

export const CREATE_GROUP = 'CREATE_GROUP';
export const GROUP_FAILURE = 'GROUP_FAILURE';
export const DISPLAY_CREATE_GROUP_FORM = 'DISPLAY_CREATE_GROUP_FORM';
export const CLOSE_CREATE_GROUP_FORM = 'CLOSE_CREATE_GROUP_FORM';
export const ADD_MENTOR_TO_GROUP = 'ADD_MENTOR_TO_GROUP';
export const ADD_MENTEE_TO_GROUP = 'ADD_MENTEE_TO_GROUP';
export const ADDING_MENTEES_TO_GROUP_IN_PROGRESS = 'ADDING_MENTEES_TO_GROUP_IN_PROGRESS';
export const ADDING_MENTORS_TO_GROUP_IN_PROGRESS = 'ADDING_MENTORS_TO_GROUP_IN_PROGRESS';
export const CANCEL_INVITE_TO_GROUP = 'CANCEL_INVITE_TO_GROUP';

export const CREATE_SESSION = 'CREATE_SESSION';
export const DISPLAY_CREATE_SESSION_FORM = 'DISPLAY_CREATE_SESSION_FORM';
export const CLOSE_CREATE_SESSION_FORM = 'CLOSE_CREATE_SESSION_FORM';

export const PROFILE_PICTURE_SUCCESS = 'PROFILE_PICTURE_SUCCESS';
export const PROFILE_PICTURE_FAILURE = 'PROFILE_PICTURE_FAILURE';

export const HELP_QUESTION_SUCCESS = 'HELP_QUESTION_SUCCESS';
export const HELP_QUESTION_FAILURE = 'HELP_QUESTION_FAILURE';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';

export const CHANGE_TAB = 'CHANGE_TAB';
export const OPEN_TAB = 'OPEN_TAB';
export const CLOSE_TAB = 'CLOSE_TAB';

export const USER_DETAILS_FETCH = 'USER_DETAILS_FETCH';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';

export const GROUP_FETCH = 'GROUP_FETCH';
export const GROUP_FETCH_SUCCESS = 'GROUP_FETCH_SUCCESS';
